# Name of your application. Used to uniquely configure containers.
service: blog

# Name of the container image.
image: andremaha/blog

# Deploy to these servers.
servers:
  web:
    - 159.223.234.130
  # job:
  #   hosts:
  #     - 159.223.234.130
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt.
proxy:
  ssl: true
  host: toktok.news

# Use GitHub Container Registry.
registry:
  server: ghcr.io
  username: andremaha
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

# Aliases for common commands.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "blog_storage:/rails/storage"

# Bridge fingerprinted assets between versions.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
